version: "3.8"

services:
  monolithic-api:
    build:
      context: ./MonolithicApi
      dockerfile: Dockerfile
    container_name: monolithic_api
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  softdelete-api:
    build:
      context: ./SoftDeleteApi
      dockerfile: Dockerfile
    container_name: softdelete_api
    ports:
      - "5001:5001"
    volumes:
      - db-data:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - monolithic-api
      - softdelete-api
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
